default:
  image: stargazernex/lbproject:v5

variables:
  LINT_OUTPUT: "lint_results.json"
  PREVIOUS_LINT_OUTPUT: "previous_lint_results.json"
  DATASET: "path/to/dataset"  # Define the dataset path
  SCORING_MATRIX: "path/to/scoring_matrix"  # Define the scoring matrix path

stages:
  - lint
  - analyze
  - test

flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 --config custom-flake8.conf code4pipeline.py || true
    - flake8 . --format=json --output-file=$LINT_OUTPUT || true
  artifacts:
    paths:
      - $LINT_OUTPUT
    when: always
    expire_in: 1 day

analyze:
  stage: analyze
  dependencies:
    - flake8
  script:
    - echo "comparing lint results..."
    - if [ -f $PREVIOUS_LINT_OUTPUT ]; then
        python compare_lint.py $PREVIOUS_LINT_OUTPUT $LINT_OUTPUT;
      else
        echo "No previous results to compare.";
      fi
    - cp $LINT_OUTPUT $PREVIOUS_LINT_OUTPUT
  artifacts:
    paths:
      - $PREVIOUS_LINT_OUTPUT
    when: always
    expire_in: 1 day

test:
  stage: test
  script:
    - echo "Running code4pipeline.py script"
    - python code4pipeline.py $DATASET $SCORING_MATRIX
    - OUTPUT_DIR="MSA_Info_$(basename $DATASET)"
    - |
      if [ -d "$OUTPUT_DIR" ]; then
        echo "Test passed: $OUTPUT_DIR exists.";
      else
        echo "Test failed: $OUTPUT_DIR does not exist.";
        exit 1;
      fi
