default:
  image: stargazernex/lbproject:v3

stages:
  - lint
  - test


flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 src/


test:
  stage: test
  script:
    - echo python manage.py test