default:
  image: stargazernex/lbproject:v3

variables:
  LINT_OUTPUT: "lint_results.json"
  PREVIOUS_LINT_OUTPUT: "previous_lint_results.json"


stages:
  - lint
  - analyze
  - test


flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 --config custom-flake8.conf demo_script.py || true
    - flake8 --config custom-flake8.conf Scripts/ || true
#    - flake8 --config custom-flake8.conf Comparison_of_MSA_Softwares_Part1/ || true
#    - flake8 --config custom-flake8.conf Comparison_of_MSA_Softwares_Part2/ || true
    - flake8 . --format=json --output-file=$LINT_OUTPUT || true
  artifacts:
    paths:
      - $LINT_OUTPUT
    when: always
    expire_in: 1 day


analyze:
  stage: analyze
  dependencies:
    - flake8
  script:
    - echo "comparing lint results..."
    - if [ -f $PREVIOUS_LINT_OUTPUT ]; then
        python compare_lint.py $PREVIOUS_LINT_OUTPUT $LINT_OUTPUT;
      else
        echo "No previous results to compare.";
      fi
    - cp $LINT_OUTPUT $PREVIOUS_LINT_OUTPUT
  artifacts:
    paths:
      - $PREVIOUS_LINT_OUTPUT
    when: always
    expire_in: 1 day

test:
  stage: test
  script:
    - python manage.py test || echo "No tests defined yet."