default:
  image: stargazernex/lbproject:v3

stages:
  - lint
  - test


flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 --config ~/.config/flake8/
    - flake8 Comparison_of_MSA_Softwares_Part1/
    - flake8 Comparison_of_MSA_Softwares_Part2/


test:
  stage: test
  script:
    - echo python manage.py test