default:
  image: python:3.9

stages:
  - lint
  - test
  - deploy


flake8:
  stage: lint
  script:
    - python --version
    - pip install flake8
    - flake8 src/
  only:
    - merge_requests


test:
  stage: test
  script:
    - echo python manage.py test
  only:
    - merge_requests

deploy:
  stage: deploy
  script:
    - echo "Deploying now!"
  only:
    - merge_requests